sudo: required
services:
  - docker

before_install:
  - docker build -t michael-knight/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michael-knight/docker-react npm run test -- --coverage

language: generic 

after_success:
  - docker build -t michael-knight/multi-client ./client
  - docker build -t michael-knight/multi-nginx ./nginx
  - docker build -t michael-knight/multi-server ./server
  - docker build -t michael-knight/multi-worker ./worker

  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push michael-knight/multi-client
  - docker push michael-knight/multi-nginx
  - docker push michael-knight/multi-server
  - docker push michael-knight/multi-worker