version: "3"

services: 
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      context: "./server"
      dockerfile: Dockerfile.dev
    volumes: 
        -  /app/node_modules
        -  ./server:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis
      - REDIS_POST=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports: 
      - '3050:80'
    depends_on:
      - api
      - client
      #
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev
    # ports:
    #   - "3000:3000"
    # volumes: 
    #   -  /app/node_modules
    #   -  .:/app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
  # redis:
  # server:
    #env variables
    #port mapping
    #volumes for 
